# Generated by Django 5.2.13 on 2026-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Konten (HTML)')),
                ('main_image', models.ImageField(upload_to='articles/', verbose_name='Gambar Utama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(verbose_name='Sejarah')),
                ('vision', models.TextField(verbose_name='Visi')),
                ('mission', models.TextField(verbose_name='Misi')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone', models.CharField(max_length=50, verbose_name='No HP')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='File Gambar')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Gambar')),
            ],
        ),
    ]
